import seoMeta from "./seoMeta.json";

export const gymConfig = {
  name: "DEEP.FIT",
  nameJa: "ディープフィット",
  tagline: "動いて、整えて、気づけば続く。",
  subtitle: "サーキット×キックボクシングフィットネスジム",
  phone: "06-7777-7853",
  email: "sakitomokideep@icloud.com",
  address: "〒660-0801 兵庫県尼崎市長洲東通1–9-25 2F DEEP.FIT",
  addressShort: "兵庫県尼崎市長洲東通1–9-25 2F",
  access: [
    "JR尼崎駅 徒歩10分",
    "駐輪スペースあり（バイクも可）",
  ],
  hours: {
    weekday: "10:00 - 13:00 / 17:00 - 22:00（パーソナル 13:00 - 17:00）",
    weekdayPersonal: "13:00 - 17:00（パーソナル・予約制）",
    saturday: "10:00 - 22:00",
    sunday: "10:00 - 22:00",
    closed: "木曜日・祝日",
  },
  hoursDisplay: [
    { label: "平日", time: "10:00 - 13:00 / 17:00 - 22:00" },
    { label: "　パーソナル", time: "13:00 - 17:00（予約制）" },
    { label: "　キッズ（月火水金）", time: "15:00 - 17:00" },
    { label: "土・日", time: "10:00 - 14:00" },
    { label: "　土キッズ（親子）", time: "14:00 - 15:00" },
    { label: "　土パーソナル", time: "15:00 - 22:00" },
    { label: "　日パーソナル", time: "14:00 - 22:00" },
    { label: "定休日", time: "木曜日・祝日" },
  ],
  sns: {
    instagram: "https://www.instagram.com/deep.amagasaki/",
    twitter: "https://x.com",
    line: "https://lin.ee/uqfaBm6",
  },
  googleMapsUrl: "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3279.1523061255643!2d135.4332379!3d34.7265551!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6000efdad0e9e859%3A0x4321cf1e4177f1fd!2sDEEP.FIT%20CIRCUIT%20%C3%97KICKBOXING%20GYM!5e0!3m2!1sja!2sjp!4v1775797181640!5m2!1sja!2sjp",
  trialLesson: {
    price: "¥1,500",
    priceOriginal: "¥1,500",
    priceNumber: 1500,
    instagramFree: true,
  },
  membership: [
    {
      name: "DEEPスタンダード会員",
      subtitle: "Full Time",
      femalePrice: "¥10,000",
      femalePriceTaxNote: "（税込 ¥11,000/月）",
      malePrice: "¥12,000",
      malePriceTaxNote: "（税込 ¥13,200/月）",
      priceNote: "/ 月",
      popular: true,
      benefits: ["全時間帯利用可能", "全クラス受け放題", "グローブ無料貸出", "パワーラック使用可"],
    },
    {
      name: "月8回会員",
      subtitle: "8 Times / Month",
      femalePrice: "¥8,000",
      femalePriceTaxNote: "（税込 ¥8,800/月）",
      malePrice: "¥10,000",
      malePriceTaxNote: "（税込 ¥11,000/月）",
      priceNote: "/ 月",
      popular: false,
      benefits: ["全時間帯利用可能", "月8回まで", "グローブ無料貸出", "パワーラック使用可"],
    },
    {
      name: "U-22会員",
      subtitle: "Under 22 / 通い放題",
      femalePrice: "¥8,000",
      femalePriceTaxNote: "（税込 ¥8,800/月）",
      malePrice: "¥8,000",
      malePriceTaxNote: "（税込 ¥8,800/月）",
      priceNote: "/ 月",
      popular: false,
      benefits: ["全時間帯利用可能", "全クラス受け放題", "グローブ無料貸出", "パワーラック使用可"],
    },
  ],
  premiumMembership: {
    name: "DEEPプラス会員",
    subtitle: "1年以上継続の方限定・通い放題",
    condition: "1年以上継続",
    malePrice: "¥9,000",
    malePriceTaxNote: "（税込 ¥9,900/月）",
    femalePrice: "¥8,000",
    femalePriceTaxNote: "（税込 ¥8,800/月）",
    priceNote: "/ 月",
    benefits: ["全時間帯利用可能", "全クラス受け放題", "グローブ無料貸出", "パワーラック使用可"],
  },
  lightMembership: {
    name: "DEEPライト会員",
    subtitle: "半年以上継続の方限定・通い放題",
    condition: "半年以上継続",
    malePrice: "¥11,000",
    malePriceTaxNote: "（税込 ¥12,100/月）",
    femalePrice: "¥9,000",
    femalePriceTaxNote: "（税込 ¥9,900/月）",
    priceNote: "/ 月",
    benefits: ["全時間帯利用可能", "全クラス受け放題", "グローブ無料貸出", "パワーラック使用可"],
  },
  kidsMembership: [
    { name: "月4回", price: "¥6,000", priceTaxNote: "（税込 ¥6,600/月）", note: "/ 月" },
    { name: "通い放題", price: "¥8,000", priceTaxNote: "（税込 ¥8,800/月）", note: "/ 月" },
    { name: "親子キック会員", price: "¥6,000", priceTaxNote: "（税込 ¥6,600/月）", note: "2名まで / 月" },
  ],
  programs: [
    { name: "ヨガ", subtitle: "Yoga", description: "呼吸と共にゆっくりと体をほぐし、心身のバランスを整えるプログラムです。", image: "/images/program-card-yoga.webp" },
    { name: "キックボクササイズ", subtitle: "Kickboxercise", description: "キックボクシングの動きを取り入れた、楽しく汗を流せるエクササイズです。" },
    { name: "アニマルフロー", subtitle: "Animal Flow", description: "動物の動きを模した全身運動で、柔軟性や体幹を鍛えるトレーニングです。" },
  ],
  programPricing: {
    memberPrice: "¥1,500",
    nonMemberPrice: "¥2,000",
    note: "1レッスン",
    schedule: "各プログラム月1回開催。開催日はInstagramでご案内いたします。",
  },
  personalTraining: {
    duration: "60分",
    price: "¥5,000",
    priceTaxNote: "（税込 ¥5,500）",
    note: "ペアでも同料金",
  },
  equipment: [
    "オールインパワーラック",
    "サンドバック 4本",
    "グローブ無料貸出",
    "更衣室完備",
    "近隣駐車場",
  ],
  joinFee: "¥10,000",
  joinFeeTaxNote: "（税込 ¥11,000）",
  stats: [
    { value: 500, label: "会員数", suffix: "+" },
    { value: 8, label: "運営実績", suffix: "年+" },
    { value: 15, label: "クラス/週", suffix: "+" },
    { value: 5, label: "プロ在籍", suffix: "名" },
  ],
};

export const seoConfig = {
  siteName: "DEEP.FIT サーキットトレーニング×キックボクシングジム",
  siteUrl: "https://deep-amagasaki.com",
  locale: "ja_JP",
  keywords: "キックボクシング, サーキットトレーニング, 尼崎, JR尼崎, 兵庫県, ダイエット, フィットネス, 初心者歓迎, 女性歓迎, 無料体験, パーソナルトレーニング, ボディメイク, ジム",
  ogImage: "/images/og-image.jpg",
  pages: {
    home: seoMeta["/"],
    about: seoMeta["/about"],
    schedule: seoMeta["/schedule"],
    kids: seoMeta["/kids"],
    program: seoMeta["/program"],
    instructors: seoMeta["/instructors"],
    contact: seoMeta["/contact"],
  },
};
