// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/deepfit-theme/CleanLight.tsx": () => import("../components/mockups/deepfit-theme/CleanLight.tsx"),
  "./components/mockups/deepfit-theme/WarmBeige.tsx": () => import("../components/mockups/deepfit-theme/WarmBeige.tsx")
};
