export const gymConfig = {
  name: "DEEP.FIT",
  nameJa: "ディープフィット",
  tagline: "動いて、整えて、気づけば続く。",
  subtitle: "サーキット×キックボクシングフィットネスジム",
  phone: "06-7777-7853",
  email: "sakitomokideep@icloud.com",
  address: "〒660-0801 兵庫県尼崎市長洲東通1–9-25 2F DEEP.FIT",
  addressShort: "兵庫県尼崎市長洲東通1–9-25 2F",
  access: [
    "JR尼崎駅 徒歩10分",
  ],
  hours: {
    weekday: "10:00 - 13:00 / 17:00 - 22:00（パーソナル 13:00 - 17:00）",
    weekdayPersonal: "13:00 - 17:00（パーソナル・予約制）",
    saturday: "10:00 - 22:00",
    sunday: "10:00 - 22:00",
    closed: "木曜日・祝日",
  },
  hoursDisplay: [
    { label: "平日", time: "10:00 - 13:00 / 17:00 - 22:00" },
    { label: "　パーソナル", time: "13:00 - 17:00（予約制）" },
    { label: "　火曜キッズ", time: "17:00 - 18:00" },
    { label: "土・日", time: "10:00 - 14:00" },
    { label: "　土キッズ", time: "14:00 - 15:00" },
    { label: "　土パーソナル", time: "15:00 - 22:00" },
    { label: "　日パーソナル", time: "14:00 - 22:00" },
    { label: "定休日", time: "木曜日・祝日" },
  ],
  sns: {
    instagram: "https://www.instagram.com/deep.amagasaki/",
    twitter: "https://x.com",
    line: "https://lin.ee/uqfaBm6",
  },
  googleMapsUrl: "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3279.1523061255643!2d135.4332379!3d34.7265551!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6000efdad0e9e859%3A0x4321cf1e4177f1fd!2sDEEP.FIT%20CIRCUIT%20%C3%97KICKBOXING%20GYM!5e0!3m2!1sja!2sjp!4v1775797181640!5m2!1sja!2sjp",
  trialLesson: {
    price: "¥1,500",
    priceOriginal: "¥1,500",
    priceNumber: 1500,
    instagramFree: true,
  },
  membership: [
    {
      name: "フルタイム会員",
      subtitle: "Full Time",
      femalePrice: "¥11,000",
      malePrice: "¥13,200",
      priceNote: "/ 月（税込）",
      popular: true,
      benefits: ["全時間帯利用可能", "全クラス受け放題", "グローブ無料貸出", "パワーラック使用可"],
    },
    {
      name: "月8回会員",
      subtitle: "8 Times / Month",
      femalePrice: "¥8,800",
      malePrice: "¥11,000",
      priceNote: "/ 月（税込）",
      popular: false,
      benefits: ["全時間帯利用可能", "月8回まで", "グローブ無料貸出", "パワーラック使用可"],
    },
    {
      name: "学生応援会員",
      subtitle: "Student（大学生可）",
      femalePrice: "¥8,800",
      malePrice: "¥8,800",
      priceNote: "/ 月（税込）",
      popular: false,
      benefits: ["全時間帯利用可能", "全クラス受け放題", "グローブ無料貸出", "パワーラック使用可"],
    },
  ],
  kidsMembership: [
    { name: "月4回", price: "¥6,600", note: "/ 月（税込）" },
    { name: "月8回", price: "¥8,800", note: "/ 月（税込）" },
  ],
  personalTraining: {
    duration: "60分",
    price: "¥5,500",
    note: "ペアでも同料金（税込）",
  },
  equipment: [
    "オールインパワーラック",
    "サンドバック 4本",
    "グローブ無料貸出",
    "更衣室完備",
    "近隣駐車場",
  ],
  joinFee: "¥10,000",
  stats: [
    { value: 500, label: "会員数", suffix: "+" },
    { value: 8, label: "運営実績", suffix: "年+" },
    { value: 15, label: "クラス/週", suffix: "+" },
    { value: 5, label: "プロ在籍", suffix: "名" },
  ],
};

export const seoConfig = {
  siteName: "DEEP.FIT サーキット×キックボクシングジム",
  siteUrl: "https://deep-amagasaki.com",
  locale: "ja_JP",
  keywords: "キックボクシング, サーキットトレーニング, 尼崎, JR尼崎, 兵庫県, ダイエット, フィットネス, 初心者歓迎, 女性歓迎, 無料体験, パーソナルトレーニング, ボディメイク, ジム",
  ogImage: "/images/og-image.jpg",
  pages: {
    home: {
      title: "JR尼崎のキックボクシングジムならDEEP.FIT｜初心者・女性歓迎・無料体験受付中",
      description: "DEEP.FITはJR尼崎駅徒歩10分のサーキット×キックボクシングジムです。初心者・女性・一人参加でも通いやすく、綺麗で広い空間と個室スミスマシンも完備。無料体験受付中。",
      h1: "JR尼崎で初心者・女性も通いやすいキックボクシングジム",
    },
    about: {
      title: "DEEP.FITってどんなジム？｜綺麗で広い空間・女性も通いやすい尼崎のキックボクシングジム",
      description: "綺麗で広い空間、和気藹々とした雰囲気、個室スミスマシン完備。DEEP.FITは初心者や女性でも通いやすく、一人で集中したい日も楽しく動きたい日も選べるジムです。",
    },
    schedule: {
      title: "クラス紹介｜初心者向けフィットネス・パーソナル・キッズクラス｜DEEP.FIT 尼崎",
      description: "DEEP.FITのクラス紹介ページです。初心者向けフィットネス、パーソナルトレーニング、キッズクラスなど、目的に合わせて選べるクラスをご案内します。",
    },
    instructors: {
      title: "インストラクター紹介｜DEEP.FIT 尼崎",
      description: "DEEP.FITのインストラクター紹介です。初心者や女性でも安心して通えるよう、丁寧なサポートを大切にしています。",
    },
    contact: {
      title: "無料体験・お問い合わせ｜DEEP.FIT 尼崎",
      description: "DEEP.FITの無料体験予約・お問い合わせページです。見学だけでもOK。運動が久しぶりの方や初心者の方もお気軽にご相談ください。",
    },
  },
};
